// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// 
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBizJ09pQO3IYmBBRoPMdxUtJMZLlGE_Ss',
    appId: '1:883277163486:web:409d55699071cd02ab0b4f',
    messagingSenderId: '883277163486',
    projectId: 'project-fire-baseaapp',
    authDomain: 'project-fire-baseaapp.firebaseapp.com',
    storageBucket: 'project-fire-baseaapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBizJ09pQO3IYmBBRoPMdxUtJMZLlGE_Ss',
    appId: '1:883277163486:android:409d55699071cd02ab0b4f',
    messagingSenderId: '883277163486',
    projectId: 'project-fire-baseaapp',
    storageBucket: 'project-fire-baseaapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBizJ09pQO3IYmBBRoPMdxUtJMZLlGE_Ss',
    appId: '1:883277163486:ios:409d55699071cd02ab0b4f',
    messagingSenderId: '883277163486',
    projectId: 'project-fire-baseaapp',
    storageBucket: 'project-fire-baseaapp.firebasestorage.app',
    iosBundleId: 'com.example.myproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBizJ09pQO3IYmBBRoPMdxUtJMZLlGE_Ss',
    appId: '1:883277163486:ios:409d55699071cd02ab0b4f',
    messagingSenderId: '883277163486',
    projectId: 'project-fire-baseaapp',
    storageBucket: 'project-fire-baseaapp.firebasestorage.app',
    iosBundleId: 'com.example.myproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBizJ09pQO3IYmBBRoPMdxUtJMZLlGE_Ss',
    appId: '1:883277163486:web:409d55699071cd02ab0b4f',
    messagingSenderId: '883277163486',
    projectId: 'project-fire-baseaapp',
    authDomain: 'project-fire-baseaapp.firebaseapp.com',
    storageBucket: 'project-fire-baseaapp.firebasestorage.app',
  );
}
